// <auto-generated />
using Easy.Core.Flow.EFCoreBase.BaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Easy.Core.Flow.EFCoreBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201125144923_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Easy.Core.Flow.EFCoreBase.Module.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Blog");
                });

            modelBuilder.Entity("Easy.Core.Flow.EFCoreBase.Module.ResBlog", b =>
                {
                    b.HasBaseType("Easy.Core.Flow.EFCoreBase.Module.Blog");

                    b.Property<string>("ResUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ResBlog");
                });

            modelBuilder.Entity("Easy.Core.Flow.EFCoreBase.Module.SpecialBlog", b =>
                {
                    b.HasBaseType("Easy.Core.Flow.EFCoreBase.Module.Blog");

                    b.Property<string>("SpecialUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("SpecialBlog");
                });
#pragma warning restore 612, 618
        }
    }
}
